/*
 * inventoryContentPanel.java
 *
 * Created on Mar 28, 2010, 3:10:55 PM
 */

package LunchInventory;

/**
 *
 * @author Master
 */

import javax.swing.BorderFactory;

public class inventoryContentPanel extends javax.swing.JPanel {

    int ID;

        /** Creates new form inventoryContentPanel */
	public inventoryContentPanel() {
            super();
            initComponents();
            setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputTField = new javax.swing.JTextField();
        hsAddButton = new javax.swing.JButton();
        hsSubButton = new javax.swing.JButton();
        hsQtyTField = new javax.swing.JTextField();
        nameTField = new javax.swing.JTextField();
        categoryIDField = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        priceTField = new javax.swing.JTextField();
        elAddButton = new javax.swing.JButton();
        elSubButton = new javax.swing.JButton();
        elQtyTField = new javax.swing.JTextField();

        setMinimumSize(getPreferredSize());
        setPreferredSize(new java.awt.Dimension(550, 35));

        inputTField.setText("1");
        inputTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTFieldActionPerformed(evt);
            }
        });

        hsAddButton.setText("+");
        hsAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hsAddButtonActionPerformed(evt);
            }
        });

        hsSubButton.setText("-");
        hsSubButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hsSubButtonActionPerformed(evt);
            }
        });

        hsQtyTField.setEditable(false);

        nameTField.setEditable(true);
        nameTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTFieldActionPerformed(evt);
            }
        });

        categoryIDField.setEditable(false);

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        priceTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTFieldActionPerformed(evt);
            }
        });

        elAddButton.setText("+");
        elAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elAddButtonActionPerformed(evt);
            }
        });

        elSubButton.setText("-");
        elSubButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elSubButtonActionPerformed(evt);
            }
        });

        elQtyTField.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(inputTField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hsAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hsSubButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hsQtyTField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(elAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(elSubButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(elQtyTField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteButton)
                .addGap(3, 3, 3)
                .addComponent(nameTField, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceTField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(categoryIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputTField)
                    .addComponent(hsAddButton)
                    .addComponent(hsSubButton)
                    .addComponent(hsQtyTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(elAddButton)
                    .addComponent(elSubButton)
                    .addComponent(deleteButton)
                    .addComponent(nameTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(elQtyTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    protected void hsAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hsAddButtonActionPerformed

    }//GEN-LAST:event_hsAddButtonActionPerformed

    protected void hsSubButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hsSubButtonActionPerformed

    }//GEN-LAST:event_hsSubButtonActionPerformed

    protected void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed

    }//GEN-LAST:event_deleteButtonActionPerformed
	
	protected void inputTFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTFieldActionPerformed

    }//GEN-LAST:event_inputTFieldActionPerformed

	protected void priceTFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTFieldActionPerformed

	}//GEN-LAST:event_priceTFieldActionPerformed

	protected void nameTFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTFieldActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_nameTFieldActionPerformed

	protected void elAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elAddButtonActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_elAddButtonActionPerformed

	protected void elSubButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elSubButtonActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_elSubButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JTextField categoryIDField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton elAddButton;
    protected javax.swing.JTextField elQtyTField;
    private javax.swing.JButton elSubButton;
    private javax.swing.JButton hsAddButton;
    protected javax.swing.JTextField hsQtyTField;
    private javax.swing.JButton hsSubButton;
    protected javax.swing.JTextField inputTField;
    protected javax.swing.JTextField nameTField;
    protected javax.swing.JTextField priceTField;
    // End of variables declaration//GEN-END:variables

}
